# Generated by Django 5.2 on 2025-04-06 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettflixapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='season',
            name='show',
        ),
        migrations.RenameField(
            model_name='userlist',
            old_name='added_at',
            new_name='added_date',
        ),
        migrations.AlterUniqueTogether(
            name='userlist',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_year',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='trailer_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='show',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='show',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='show',
            name='release_year',
        ),
        migrations.RemoveField(
            model_name='show',
            name='trailer_url',
        ),
        migrations.RemoveField(
            model_name='show',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='movie',
            name='image_card',
            field=models.ImageField(default='movie_images/default.jpg', upload_to='movie_images/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='image_cover',
            field=models.ImageField(default='movie_images/default.jpg', upload_to='movie_images/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='movie',
            name='movies_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='posters/default.jpg', upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(default='movie_videos/default.mp4', upload_to='movie_videos/'),
        ),
        migrations.AddField(
            model_name='show',
            name='image_card',
            field=models.ImageField(default='show_images/default.jpg', upload_to='show_images/'),
        ),
        migrations.AddField(
            model_name='show',
            name='image_cover',
            field=models.ImageField(default='show_images/default.jpg', upload_to='show_images/'),
        ),
        migrations.AddField(
            model_name='show',
            name='poster',
            field=models.ImageField(default='posters/default.jpg', upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='show',
            name='release_date',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AddField(
            model_name='show',
            name='seasons',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='show',
            name='show_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='show',
            name='video',
            field=models.FileField(default='show_videos/default.mp4', upload_to='show_videos/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('science_fiction', 'Science Fiction'), ('fantasy', 'Fantasy')], default='action', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='show',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('science_fiction', 'Science Fiction'), ('fantasy', 'Fantasy')], default='action', max_length=20),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userlist',
            unique_together={('user', 'movie', 'show')},
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
