# Generated by Django 5.2 on 2025-04-07 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettflixapp', '0002_alter_season_unique_together_remove_season_show_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_card',
            field=models.ImageField(default='movie_images/default.jpg', help_text='Image should have a 2:3 aspect ratio', upload_to='movie_images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_cover',
            field=models.ImageField(default='movie_images/default.jpg', help_text='Image should have a 16:9 aspect ratio', upload_to='movie_images/'),
        ),
        migrations.AlterField(
            model_name='show',
            name='image_card',
            field=models.ImageField(default='show_images/default.jpg', help_text='Image should have a 2:3 aspect ratio', upload_to='show_images/'),
        ),
        migrations.AlterField(
            model_name='show',
            name='image_cover',
            field=models.ImageField(default='show_images/default.jpg', help_text='Image should have a 16:9 aspect ratio', upload_to='show_images/'),
        ),
        migrations.CreateModel(
            name='Movielist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nettflixapp.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
